# Generated by Django 4.0.4 on 2022-05-19 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cita', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo Cita',
            },
        ),
        migrations.CreateModel(
            name='agendamiento_citas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cita', models.DateField()),
                ('motivo_cita', models.CharField(max_length=120)),
                ('nombre_veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.veterinario')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.pacientes')),
                ('tipo_cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.tipo_cita')),
            ],
            options={
                'verbose_name': 'Agendamiento Cita',
            },
        ),
    ]
