# Generated by Django 4.0.4 on 2022-05-19 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventariado', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='receta_medica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.CharField(max_length=250)),
                ('medicina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventariado.medicina')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.agendamiento_citas')),
            ],
            options={
                'verbose_name': 'Receta Medica',
            },
        ),
    ]
