# Generated by Django 4.0 on 2022-05-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_carton_vacuna'),
    ]

    operations = [
        migrations.CreateModel(
            name='historial_clinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(max_length=45)),
                ('tipo_cita', models.CharField(max_length=45)),
                ('fecha_cita', models.DateField()),
                ('motivo_cita', models.CharField(max_length=120)),
                ('nombre_veterinario', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Historial Clinico',
            },
        ),
    ]
