# Generated by Django 4.0 on 2022-05-20 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_remove_historial_clinico_fecha_cita_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='historial_clinico',
        ),
    ]
