# Generated by Django 4.0 on 2022-05-23 21:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('servicios', '0009_delete_hospitalizacion_egreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='hospitalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingreso', models.DateTimeField(default=datetime.datetime.now)),
                ('egreso', models.DateField(blank=True)),
                ('observatorio', models.CharField(max_length=250)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.pacientes')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.veterinario')),
            ],
            options={
                'verbose_name': 'Hospitalizacion Ingreso',
            },
        ),
        migrations.DeleteModel(
            name='hospitalizacion_ingreso',
        ),
    ]
