# Generated by Django 4.0 on 2022-05-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0010_hospitalizacion_delete_hospitalizacion_ingreso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospitalizacion',
            options={'verbose_name': 'Hospitalizacion'},
        ),
        migrations.AlterField(
            model_name='hospitalizacion',
            name='egreso',
            field=models.DateField(blank=True, null=True),
        ),
    ]
