# Generated by Django 4.0.4 on 2022-05-19 20:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mascota_sexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo_mascota', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Mascota sexo',
                'verbose_name_plural': 'Mascota sexos',
            },
        ),
        migrations.CreateModel(
            name='pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('raza', models.CharField(max_length=45)),
                ('fecha_nacimiente', models.DateField()),
                ('mascota_color', models.CharField(max_length=20)),
                ('mascota_longitud', models.CharField(max_length=20)),
                ('sexo_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.mascota_sexo')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='tipo_documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo documento',
                'verbose_name_plural': 'Tipo documentos',
            },
        ),
        migrations.CreateModel(
            name='tipo_mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mascota', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo mascota',
                'verbose_name_plural': 'Tipo mascotas',
            },
        ),
        migrations.CreateModel(
            name='veterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_veterinario', models.CharField(max_length=45)),
                ('especializacion', models.CharField(max_length=45)),
                ('numero_documento', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.tipo_documento')),
            ],
            options={
                'verbose_name': 'Veterinario',
            },
        ),
        migrations.CreateModel(
            name='propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_propietario', models.CharField(max_length=45)),
                ('numero_documento', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('direccion_propietario', models.CharField(max_length=45)),
                ('celular_propietario', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('email_propietario', models.EmailField(max_length=45, unique=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.pacientes')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.tipo_documento')),
            ],
            options={
                'verbose_name': 'Propietario',
                'verbose_name_plural': 'Propietarios',
            },
        ),
        migrations.AddField(
            model_name='pacientes',
            name='tipo_mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.tipo_mascota'),
        ),
    ]
