# Generated by Django 4.0.4 on 2022-05-19 21:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vacunas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_vacuna', models.CharField(max_length=45, unique=True)),
                ('vacuna_cantidad', models.IntegerField()),
                ('vacuna_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.tipo_mascota')),
            ],
            options={
                'verbose_name': 'Vacuna',
            },
        ),
        migrations.CreateModel(
            name='medicina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_medicina', models.CharField(max_length=45, unique=True)),
                ('medicina_cantidad', models.IntegerField()),
                ('medicina_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.tipo_mascota')),
            ],
            options={
                'verbose_name': 'Medicina',
            },
        ),
        migrations.CreateModel(
            name='inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_medicina', models.IntegerField()),
                ('cantidad_vacuna', models.IntegerField()),
                ('inventario_fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('medicina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventariado.medicina')),
                ('vacuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventariado.vacunas')),
            ],
        ),
    ]
