# Generated by Django 4.0 on 2022-05-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventariado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='inventario_fecha',
            field=models.DateField(),
        ),
    ]
